print("*****BITWISE OPERATOR*****")
a=int(input("Enter 1st number: "))
b=int(input("Enter 2nd number: "))
print(a&b)
print(a|b)
#print(a~b)
print(a^b)
print(a<<b)
print(a>>b)
print("***********")
print(True&True)
print(True|True)
#print(True~True)
print(True^True)
print(True<<True)
print(True>>True)
print(True==True)
print("***********")
print(True&False)
print(True|False)
#print(True~False)
print(True^False)
print(True<<False)
print(True>>False)
print(True==False)
print("***********")
print(False&False)
print(False|False)
#print(False~False)
print(False^False)
print(False<<False)
print(False>>False)
print(False==False)

