print(10&20)
print(True&True)
#print(10.2 & 20.1)
print("***********")
print(10|20)
print(True|True)
#print(10.2 | 20.1)
print("***********")
print(True^True)
print("***********")
print(4&5)
print(4|5)
print(4^5)
print(4<<5)
print(4>>5)
#print(4~5)
print("***********")
a=-11
b=-21
print(a&b)
print(a|b)
print(a^b)
#print(a>>b)
#print(a<<b)
print(~b)
print("***********")
print(True&True)
print(True|True)
print(True^True)
print(True<<True)
print(True>>True)
print(~True)
print("***********")
print(True&False)
print(True|False)
print(True^False)
print(True<<False)
print(True>>False)
print(~False)
print("***********")
print(False&False)
print(False|False)
print(False^False)
print(False<<False)
print(False>>False)
print(~False)
print("***********")



